apiVersion: v1
data:
  .dockerconfigjson: repl{{ LicenseDockerCfg }}
kind: Secret
metadata:
  name: second-namespace-registry-secret
  namespace: repl{{ ConfigOption "namespace"}}
type: kubernetes.io/dockerconfigjson
