apiVersion: v1
data:
  .dockerconfigjson: repl{{ LicenseDockerCfg }}
kind: Secret
metadata:
  name: kotsadm-replicated-registry
  namespace: repl{{ ConfigOption "namespace"}}
type: kubernetes.io/dockerconfigjson
